UPDATE cartas SET image_url = "https://gundams.dev/i/gudamsdev.svg" WHERE card_name = "Gundams.dev";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/EXB-001.webp" WHERE card_name = "EX Base";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/exresource.webp" WHERE card_name = "EX Resource";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/GD01-004.webp" WHERE card_name = "Guncannon";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/GD01-004_p1.webp" WHERE card_name = "Guncannon";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/11/GD01-005.webp" WHERE card_name = "Unicorn Gundam (Unicorn Mode)";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/GD01-008-1.webp" WHERE card_name = "Guntank";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/GD01-009.webp" WHERE card_name = "G-Fighter";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/GD01-011.webp" WHERE card_name = "Loto";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/GD01-013.webp" WHERE card_name = "Gundam";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/GD01-015-1.webp" WHERE card_name = "Ball";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/GD01-016.webp" WHERE card_name = "Jegan";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/GD01-018.webp" WHERE card_name = "ReZEL";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/GD01-026-2.webp" WHERE card_name = "Char's Zaku II";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/GD01-026_p1.webp" WHERE card_name = "Char's Zaku II";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/GD01-028.webp" WHERE card_name = "Gundam Sandrock";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/GD01-030.webp" WHERE card_name = "Rick Dom";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/GD01-031.webp" WHERE card_name = "Gelgoog";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/GD01-034.webp" WHERE card_name = "Gundam Heavyarms";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/GD01-040.webp" WHERE card_name = "Wing Gundam";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/GD01-041.webp" WHERE card_name = "Shenlong Gundam";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/GD01-068.webp" WHERE card_name = "Perfect Strike Gundam";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/GD01-070.webp" WHERE card_name = "Gundam Aerial";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/GD01-070_p1.webp" WHERE card_name = "Gundam Aerial";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/GD01-072.webp" WHERE card_name = "Launcher Strike Gundam";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/GD01-075.webp" WHERE card_name = "Darilbalde";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/GD01-076.webp" WHERE card_name = "Michaelis";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/GD01-077.webp" WHERE card_name = "Strike Gundam";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/GD01-081.webp" WHERE card_name = "M1 Astray";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/11/GD01-088.webp" WHERE card_name = "Banagher Links";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/11/GD01-088p.webp" WHERE card_name = "Banagher Links";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/GD01-089.webp" WHERE card_name = "Riddhe Marcenas";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/GD01-091.webp" WHERE card_name = "Chang Wufei";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/11/GD01-097.webp" WHERE card_name = "Guel Jeturk";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/GD01-099.webp" WHERE card_name = "Intercept Orders";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/11/GD01-100.webp" WHERE card_name = "A Show of Resolve";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/GD01-100_p1.webp" WHERE card_name = "A Show of Resolve";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/GD01-105.webp" WHERE card_name = "Citizens, Take a Stand!";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/GD01-107.webp" WHERE card_name = "First Contact";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/GD01-107_p1.webp" WHERE card_name = "First Contact";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/GD01-117.webp" WHERE card_name = "The Witch and the Bride";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/GD01-118.webp" WHERE card_name = "Overflowing Affection";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/11/GD01-118-p.webp" WHERE card_name = "Overflowing Affection";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/GD01-120.webp" WHERE card_name = "Naval Bombardment";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/GD01-124.webp" WHERE card_name = "Side 7";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/R-001.webp" WHERE card_name = "Resource";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/R-001_p1.webp" WHERE card_name = "Resource";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/ST01-001.webp" WHERE card_name = "Gundam";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/ST01-001_p1.webp" WHERE card_name = "Gundam";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/ST01-002.webp" WHERE card_name = "Gundam (MA Form)";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/ST01-005-1.webp" WHERE card_name = "GM";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/ST01-007.webp" WHERE card_name = "Gundam Aerial (Bit on Form)";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/ST01-008.webp" WHERE card_name = "Demi Trainer";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/ST01-010.webp" WHERE card_name = "Amuro Ray";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/ST01-011.webp" WHERE card_name = "Suletta Mercury";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/ST01-011_p1.webp" WHERE card_name = "Suletta Mercury";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/ST01-012.webp" WHERE card_name = "Thoroughly Damaged";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/ST01-013.webp" WHERE card_name = "Kai's Resolve";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/ST01-015.webp" WHERE card_name = "White Base";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/ST01-016.webp" WHERE card_name = "Asticassia School of Technology, Earth House";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/ST02-001.webp" WHERE card_name = "Wing Gundam";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/ST02-001_p1.webp" WHERE card_name = "Wing Gundam";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/ST02-002.webp" WHERE card_name = "Wing Gundam (Bird Mode)";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/ST02-005.webp" WHERE card_name = "Maganac";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/ST02-010.webp" WHERE card_name = "Heero Yuy";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/ST02-012.webp" WHERE card_name = "Simultaneous Fire";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/ST02-013.webp" WHERE card_name = "Peaceful Timbre";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/ST02-015.webp" WHERE card_name = "Saint Gabriel Institute";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/ST03-001_2.webp" WHERE card_name = "Sinanju";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/ST03-003_1.webp" WHERE card_name = "Geara Zulu";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/ST03-007.webp" WHERE card_name = "Zaku I";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/ST03-008.webp" WHERE card_name = "Zaku II";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/ST03-011-1.webp" WHERE card_name = "Char Aznable";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/11/ST03-011.webp" WHERE card_name = "Char Aznable";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/ST03-016.webp" WHERE card_name = "Falmel";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/10/ST04-001.webp" WHERE card_name = "Aile Strike Gundam";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/ST04-001_p1.webp" WHERE card_name = "Aile Strike Gundam";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/ST04-002.webp" WHERE card_name = "Strike Gundam";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/ST04-005.webp" WHERE card_name = "Strike Dagger";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/11/ST04-010.webp" WHERE card_name = "Kira Yamato";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/ST04-013.webp" WHERE card_name = "Hawk of Endymion";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/ST04-015.webp" WHERE card_name = "Archangel";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/T-001.webp" WHERE card_name = "Gundam";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/T-002.webp" WHERE card_name = "Guncannon";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/T-003.webp" WHERE card_name = "Guntank";
UPDATE cartas SET image_url = "https://gogi.cardlist.dev/wp-content/uploads/2024/12/T-006.webp" WHERE card_name = "Char's Zaku II";
